services:
  nocodb:
    image: nocodb/nocodb:0.257.2
    container_name: nocodb
    restart: always
    volumes:
      - ./volumes:/usr/app/data/ 
    ports:
      - "127.0.0.1:3366:8080"
    environment:
      NC_PUBLIC_URL: https://db.nano-exp.com
